### ISSUE TITLE
ModuleNotFoundError: No module named 'urllib3'

### ISSUE THREAD

**Issue by gOOvER** [Mixaill/galaxy-integration-wargaming#19]
```
2019-11-11 18:02:24,038 - root - ERROR - Plugin exception
Traceback (most recent call last):
  File "C:\Program Files (x86)\GOG Galaxy\plugin_runner.py", line 35, in <module>
    module = importlib.import_module(filename)
  File "D:\obj\Windows-Release\37win32_Release\msi_python\zip_win32\__init__.py", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\goove\AppData\Local\GOG.com\Galaxy\plugins\installed\wargaming_v0.7.9\plugin.py", line 19, in <module>
    import urllib3
ModuleNotFoundError: No module named 'urllib3'
2019-11-11 18:04:00,610 - root - ERROR - Plugin exception
Traceback (most recent call last):
  File "C:\Program Files (x86)\GOG Galaxy\plugin_runner.py", line 35, in <module>
    module = importlib.import_module(filename)
  File "D:\obj\Windows-Release\37win32_Release\msi_python\zip_win32\__init__.py", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\goove\AppData\Local\GOG.com\Galaxy\plugins\installed\wargaming_v0.7.9\plugin.py", line 19, in <module>
    import urllib3
ModuleNotFoundError: No module named 'urllib3'

```

**Comment by Mixaill** [comment]
Did you install it from releases page? 

Is there `3rdparty` folder in `C:\Users\goove\AppData\Local\GOG.com\Galaxy\plugins\installed\wargaming_v0.7.9` ?

**Comment by gOOvER** [comment]
i installed it with the Plugin Updater: https://github.com/Slashbunny/gog-galaxy-plugin-downloader

Yes i have this folder

**Comment by Mixaill** [comment]
Please try to install via searchbox inside client

**Comment by Mixaill** [comment]
Closed due to inactivity
